site_name: Run
site_url: /
site_description: Official website of run
repo_url: https://github.com/runscripts/run
use_absolute_urls: true
copyright: Copyright &copy; 2014 with MIT License

dev_addr: '0.0.0.0:8000'
docs_dir: docs
theme: mkdocs

#include_search: true

pages:

# Index
- ['index.md']

# Get Started
- ['get_started/why_use_run.md', 'Get Started', 'Why Use Run']
- ['get_started/usage.md', 'Get Started', "Usage"]
- ['get_started/add_source.md', 'Get Started', 'Add Source']
- ['get_started/faq.md', 'Get Started', "FAQ"]

# Installation
- ['installation/source_code.md', 'Installation', 'Source Code']
- ['installation/linux.md', 'Installation', 'Linux']
- ['installation/debain.md', 'Installation', 'Debain/Ubuntu']
- ['installation/macos.md', 'Installation', 'MacOS']
- ['installation/freebsd.md', 'Installation', 'FreeBSD']
- ['installation/arm.md', 'Installation', 'ARM']

# Official Scripts
- ['official_scripts/pt-summary.md', 'Official Scripts', 'pt-summary']
- ['official_scripts/get-pip.py.md', 'Official Scripts', 'get-pip.py']

# Source List
- ['source_list/tobegit3hub_scripts.md', 'Source List', 'tobegit3hub/scripts']

# Articles
- ['articles/use_pt_summary_for_benchmark.md', 'Articles', 'Use pt-summary For Benchmark']

